### ISSUE TITLE
图11和图12挂了

### ISSUE THREAD

**Issue by lwhile** [maemual/raft-zh_cn#23]
应该是图片源的问题:

[图11源](https://camo.githubusercontent.com/a6ab17469ed9db47d7e3a242272dffc20392d177/68747470733a2f2f646e2d307830312d696f2e71626f782e6d652f726166742d25453525394225424531312e706e67)

[图12源](https://camo.githubusercontent.com/0dc1ee745b32d4ae32e58a9a09b57e6faa117cf4/68747470733a2f2f646e2d307830312d696f2e71626f782e6d652f726166742d25453525394225424531322e706e67)

@maemual  从其他地方访问是不是也会? 是的话我就把图片源换下吧

**Comment by maemual** [comment]
是打开会出现半截图片的情况么？我打开图 11 是正常的，图 12 会半截。感觉是 Github 的问题。

**Comment by lwhhhh** [comment]
@maemual 是Github的问题,我这边图片出现了半截的情况.
