### ISSUE TITLE
图片 404

### ISSUE THREAD

**Issue by zhanggang807** [maemual/raft-zh_cn#43]
RT

**Comment by yangwenmai** [comment]
哪张图片404？我这里全部都可以正常打开。

确认一下你的网络。

**Comment by zhanggang807** [comment]
Request URL: https://camo.githubusercontent.com/ad683fbaefbc0bc0fcb31b1d6ca6ca8f715c12cd/68747470733a2f2f646e2d307830312d696f2e71626f782e6d652f726166742d254535253942254245312d30312e706e67
Request Method: GET
Status Code: 404 Not Found
Remote Address: 151.101.76.133:443
Referrer Policy: no-referrer-when-downgrade



Request URL: https://camo.githubusercontent.com/56f58887801fa337b76aefde5a0578eba1e34166/68747470733a2f2f646e2d307830312d696f2e71626f782e6d652f726166742d254535253942254245392e706e67
Request Method: GET
Status Code: 404 Not Found
Remote Address: 151.101.76.133:443
Referrer Policy: no-referrer-when-downgrade

**Comment by yangwenmai** [comment]
源文件中的图片是放在七牛的，但是七牛对域名进行了回收。

比如：https://dn-0x01-io.qbox.me/raft-%E5%9B%BE4-01.png

**Comment by zhanggang807** [comment]
那何时修复？

**Comment by zhanggang807** [comment]
👍
