### ISSUE TITLE
是否可以转载中文翻译

### ISSUE THREAD

**Issue by EscapeLife** [maemual/raft-zh_cn#60]
> **希望在我的 [博客](https://www.escapelife.site) 中转载关于 `Raft` 的中文翻译**

1. 会在文章标题中显示是转载的文章
2. 会在文章首部注明转载的 `Github` 地址
3. 如果翻译禁止转载的话，我就不转载了
4. 最后，祝身体健康！

**Comment by maemual** [comment]
可以。

**Comment by EscapeLife** [comment]
@maemual Tks
