### ISSUE TITLE
non-Byzantine

### ISSUE THREAD

**Issue by lyj7890** [maemual/raft-zh_cn#68]
They ensure safety (never returning an incorrect result) _**under all non-Byzantine conditions**_, including
network delays, partitions, and packet loss, duplication, and reordering.

在所有不是特别复杂的条件下

**Comment by maemual** [comment]
拜占庭将军问题是分布式系统中一个特指的问题 
 https://zh.wikipedia.org/wiki/%E6%8B%9C%E5%8D%A0%E5%BA%AD%E5%B0%86%E5%86%9B%E9%97%AE%E9%A2%98

**Comment by lyj7890** [comment]
> 
> 
> 拜占庭将军问题是分布式系统中一个特指的问题
> https://zh.wikipedia.org/wiki/%E6%8B%9C%E5%8D%A0%E5%BA%AD%E5%B0%86%E5%86%9B%E9%97%AE%E9%A2%98

got it, tks
